// <auto-generated />
using ExpenseTracker.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTracker.DataAccess.Migrations
{
    [DbContext(typeof(GoodHabitsDbContext))]
    [Migration("20240329183047_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExpenseTracker.DataAccess.Entities.Habit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Habits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Become a francophone",
                            Name = "Learn French",
                            TenantName = "Bluewave"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Get really fit",
                            Name = "Run a marathon",
                            TenantName = "AscendTech"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Finish your book project",
                            Name = "Write every day",
                            TenantName = "CloudSphere"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Finish your book project",
                            Name = "Write every day",
                            TenantName = "DataStream"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
